apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: conjur-knative
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: secretless
        image: dev.local/conjur-knative:v1
        env:
          - name: Options__Secret
            valueFrom:
              secretKeyRef:
                name: knative-secrets
                key: optionsSecret